import { PageHeading, StatusBadge } from "@/components/Ui";
import { campaigns } from "@/lib/demo-data";

export default function CampaignsPage() {
  return <main className="page-content">
    <PageHeading eyebrow="Campaign workspace" title="活动工作台" description="将机会转换成可审核、可测量、可复盘的运营实验。系统不会自动触达客户。" action={<button className="button button-primary">新建活动草案</button>} />
    <section className="campaign-layout"><article className="card campaign-builder"><div className="card-kicker"><StatusBadge tone="warning">待审批</StatusBadge><span>来自机会 OPP-001</span></div><h2>{campaigns[0].name}</h2><p className="hero-copy">{campaigns[0].objective}</p><div className="stepper"><div className="step active"><b>1</b><span>定义目标</span></div><div className="step active"><b>2</b><span>选择人群</span></div><div className="step active"><b>3</b><span>设置实验</span></div><div className="step"><b>4</b><span>人工确认</span></div></div><div className="form-grid"><label>目标人群<div className="field-display">{campaigns[0].audience}</div></label><label>触达渠道<div className="field-display">{campaigns[0].channel}</div></label><label>活动预算<div className="field-display">{campaigns[0].budget}</div></label><label>观察周期<div className="field-display">14 天</div></label></div><div className="approval-note"><strong>审批前检查</strong><span>确认人群规模、优惠成本、对照组与停止条件。审批仅生成执行清单，不代表系统已向客户发送内容。</span></div><div className="button-row"><button className="button button-primary">提交人工审批</button><button className="button button-ghost">保存为草案</button></div></article><aside className="card timeline-card"><p className="eyebrow">Approval trail</p><h3>操作留痕</h3><ol className="timeline"><li><b>Agent 生成方案</b><span>包含人群证据、预算和预期指标</span></li><li><b>运营确认参数</b><span>待完成 · 需人工确认</span></li><li><b>渠道平台执行</b><span>未连接 · 不会自动发送</span></li><li><b>归因与复盘</b><span>对照组完成后计算</span></li></ol></aside></section>
    <section className="section-heading"><div><p className="eyebrow">Campaigns</p><h2>活动列表</h2></div></section><section className="card table-card"><div className="table-head"><span>活动</span><span>渠道</span><span>预算</span><span>阶段</span></div>{campaigns.map((item) => <div className="table-row campaign-row" key={item.id}><div><strong>{item.name}</strong><small>{item.objective}</small></div><span>{item.channel}</span><strong>{item.budget}</strong><StatusBadge tone={item.state === "进行中" ? "success" : "warning"}>{item.state}</StatusBadge></div>)}</section>
  </main>;
}
