"use client";

import { useState } from "react";
import { PageHeading, StatusBadge } from "@/components/Ui";
import { campaigns } from "@/lib/demo-data";

export default function CampaignsPage() {
  const [stage, setStage] = useState<"draft" | "review" | "saved">("draft");
  const [showResults, setShowResults] = useState(false);
  return <main className="page-content">
    <PageHeading eyebrow="Campaign workspace" title="活动工作台" description="将机会转换成可审核、可测量、可复盘的运营实验。系统不会自动触达客户。" action={<button className="button button-primary" onClick={() => document.getElementById("campaign-builder")?.scrollIntoView({ behavior: "smooth" })}>新建活动草案</button>} />
    <section className="campaign-layout" id="campaign-builder"><article className="card campaign-builder"><div className="card-kicker"><StatusBadge tone={stage === "review" ? "accent" : "warning"}>{stage === "review" ? "审批中" : stage === "saved" ? "已保存草案" : "待审批"}</StatusBadge><span>来自机会 OPP-001</span></div><h2>{campaigns[0].name}</h2><p className="hero-copy">{campaigns[0].objective}</p><div className="stepper"><div className="step active"><b>1</b><span>定义目标</span></div><div className="step active"><b>2</b><span>选择人群</span></div><div className="step active"><b>3</b><span>设置实验</span></div><div className={`step ${stage === "review" ? "active" : ""}`}><b>4</b><span>人工确认</span></div></div><div className="form-grid"><label>目标人群<div className="field-display">{campaigns[0].audience}</div></label><label>触达渠道<div className="field-display">{campaigns[0].channel}</div></label><label>活动预算<div className="field-display">{campaigns[0].budget}</div></label><label>观察周期<div className="field-display">14 天</div></label></div><div className="experiment-box"><div><strong>实验设计</strong><span>建议随机分组，控制季节性干扰</span></div><div className="experiment-grid"><div><small>实验组</small><b>100 人</b></div><div><small>对照组</small><b>100 人</b></div><div><small>停止条件</small><b>ROI &lt; 0</b></div></div></div><div className="approval-note"><strong>审批前检查</strong><span>确认人群规模、优惠成本、对照组与停止条件。审批仅生成执行清单，不代表系统已向客户发送内容。</span></div><div className="button-row"><button className="button button-primary" onClick={() => setStage("review")}>{stage === "review" ? "已提交审批 ✓" : "提交人工审批"}</button><button className="button button-ghost" onClick={() => setStage("saved")}>{stage === "saved" ? "已保存 ✓" : "保存为草案"}</button></div>{stage === "review" && <div className="inline-success">✓ 已进入人工审批队列，等待运营人员确认后才能执行。</div>}</article><aside className="card timeline-card"><p className="eyebrow">Approval trail</p><h3>操作留痕</h3><ol className="timeline"><li><b>Agent 生成方案</b><span>包含人群证据、预算和预期指标</span></li><li><b>运营确认参数</b><span>{stage === "review" ? "已提交 · 等待审批" : "待完成 · 需人工确认"}</span></li><li><b>渠道平台执行</b><span>未连接 · 不会自动发送</span></li><li><b>归因与复盘</b><span>对照组完成后计算</span></li></ol></aside></section>
    <section className="section-heading"><div><p className="eyebrow">Campaigns</p><h2>活动列表</h2></div><button className="text-link" onClick={() => setShowResults(!showResults)}>{showResults ? "收起结果" : "查看演示结果"} →</button></section><section className="card table-card"><div className="table-head"><span>活动</span><span>渠道</span><span>预算</span><span>阶段</span></div>{campaigns.map((item, index) => <div className="table-row campaign-row" key={item.id}><div><strong>{item.name}</strong><small>{item.objective}</small></div><span>{item.channel}</span><strong>{item.budget}</strong><StatusBadge tone={index === 0 && stage === "review" ? "accent" : item.state === "进行中" ? "success" : "warning"}>{index === 0 && stage === "review" ? "审批中" : item.state}</StatusBadge></div>)}</section>{showResults && <section className="card results-preview"><div><p className="eyebrow">DEMO ATTRIBUTION</p><h2>结果回执预览</h2><p>以下为演示数据。正式版本需要接入渠道事件和订单回执后计算。</p></div><div className="result-metrics"><div><span>实验组转化</span><strong>20.0%</strong></div><div><span>对照组转化</span><strong>10.0%</strong></div><div><span>提升</span><strong className="metric-positive">+10.0pp</strong></div><div><span>ROI</span><strong>0.0%</strong></div></div></section>}
  </main>;
}
