"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { PageHeading, StatusBadge } from "@/components/Ui";
import { useI18n } from "@/components/I18n";
import styles from "./learning-results.module.css";

const API_BASE_URL = process.env.NEXT_PUBLIC_REVENUEOPS_API_URL?.replace(/\/$/, "");
type Result = { treatment_conversion:number; control_conversion:number; conversion_uplift_pp:number; incremental_orders:number; incremental_revenue:number; roi:number|null; currency:string; attribution_window_days:number; revenue_net_of_refunds:boolean; source:string };
type Task = { task_id:string; title?:string; status:string; budget?:number; source_diagnosis?:{source?:string}; execution?:{mode?:string}; result?:Result };
const initialForm = { treatment_users:"100", treatment_orders:"0", treatment_revenue:"0", control_users:"100", control_orders:"0", control_revenue:"0", cost:"0", currency:"USD", revenue_net_of_refunds:false };
const money = (value:number, currency="USD") => new Intl.NumberFormat("zh-CN", { style:"currency", currency, maximumFractionDigits:0 }).format(value);

export default function LearningPage() {
  const { t } = useI18n();
  const [task,setTask]=useState<Task|null>(null); const [state,setState]=useState<"loading"|"signed-out"|"empty"|"ready">("loading");
  const [form,setForm]=useState(initialForm); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  useEffect(()=>{ const token=sessionStorage.getItem("revenueops_access_token"); if(!token||!API_BASE_URL){Promise.resolve().then(()=>setState("signed-out"));return;}
    fetch(`${API_BASE_URL}/v1/tasks`,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>r.ok?r.json():Promise.reject()).then(data=>{const realTask=(Array.isArray(data.tasks)?data.tasks:[]).find((item:Task)=>item.source_diagnosis?.source==="consented_reactivation_aggregate"&&item.execution?.mode==="manual_handoff"&&["confirmed","completed"].includes(item.status))??null;setTask(realTask);setState(realTask?"ready":"empty");if(realTask?.budget!=null)setForm(current=>({...current,cost:String(realTask.budget)}));}).catch(()=>{setState("empty");setMessage("暂时无法读取真实执行结果，请稍后重试。");}); },[]);
  async function submitResult(){if(!task||!API_BASE_URL)return;const token=sessionStorage.getItem("revenueops_access_token");if(!token){setState("signed-out");return;}setSaving(true);setMessage("正在计算归因结果…");const payload={...form,treatment_users:Number(form.treatment_users),treatment_orders:Number(form.treatment_orders),treatment_revenue:Number(form.treatment_revenue),control_users:Number(form.control_users),control_orders:Number(form.control_orders),control_revenue:Number(form.control_revenue),cost:Number(form.cost)};const response=await fetch(`${API_BASE_URL}/v1/tasks/${task.task_id}/observed-result`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));setSaving(false);if(!response.ok){setMessage(data.error??"结果回传失败。");return;}setTask(data.task);setMessage("已记录商家回传的分组汇总结果，未上传任何客户名单。");}
  const result=task?.result;
  return <main className="page-content"><PageHeading eyebrow="Measurement & learning" title={t("learningTitle")} description={t("learningDescription")} />
    <section className={`card ${styles.realPanel}`} aria-labelledby="real-result-heading"><div className={styles.panelHead}><div><p className="eyebrow">REAL PILOT RESULT</p><h2 id="real-result-heading">真实执行归因</h2><p>仅接收实验组与对照组的汇总数字，不接收客户身份或联系方式。</p></div><StatusBadge tone={result?"success":"accent"}>{result?"已回传":"待回传"}</StatusBadge></div>
      {state==="loading"&&<div className={styles.empty}>正在读取真实执行任务…</div>}
      {state==="signed-out"&&<div className={styles.empty}><strong>需要登录当前试点账号</strong><span>登录后才能读取该账号的执行结果。</span><Link className="button button-ghost" href="/data">前往数据连接</Link></div>}
      {state==="empty"&&<div className={styles.empty}><strong>还没有可回传结果的真实任务</strong><span>{message||"请先在活动工作台确认真实执行包。"}</span><Link className="button button-ghost" href="/campaigns">前往活动工作台</Link></div>}
      {state==="ready"&&task&&!result&&<><div className={styles.taskStrip}><span>已确认执行包</span><strong>{task.title}</strong><small>数据来源：商家手工回传的分组汇总结果</small></div><div className={styles.groupGrid}>
        <fieldset><legend>实验组</legend><label>人数<input type="number" min="1" value={form.treatment_users} onChange={e=>setForm({...form,treatment_users:e.target.value})}/></label><label>订单数<input type="number" min="0" value={form.treatment_orders} onChange={e=>setForm({...form,treatment_orders:e.target.value})}/></label><label>收入<input type="number" min="0" step="0.01" value={form.treatment_revenue} onChange={e=>setForm({...form,treatment_revenue:e.target.value})}/></label></fieldset>
        <fieldset><legend>对照组</legend><label>人数<input type="number" min="1" value={form.control_users} onChange={e=>setForm({...form,control_users:e.target.value})}/></label><label>订单数<input type="number" min="0" value={form.control_orders} onChange={e=>setForm({...form,control_orders:e.target.value})}/></label><label>收入<input type="number" min="0" step="0.01" value={form.control_revenue} onChange={e=>setForm({...form,control_revenue:e.target.value})}/></label></fieldset>
      </div><div className={styles.costRow}><label>活动实际成本<input type="number" min="0" step="0.01" value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})}/></label><label>币种<input maxLength={3} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label className={styles.check}><input type="checkbox" checked={form.revenue_net_of_refunds} onChange={e=>setForm({...form,revenue_net_of_refunds:e.target.checked})}/>收入已扣除退款</label></div><div className={styles.submitRow}><p>提交后任务将标记为已完成。结果为商家自行回传，平台尚未独立核验。</p><button className="button button-primary" disabled={saving} onClick={submitResult}>{saving?"计算中…":"回传并计算归因"}</button></div>{message&&<p className="inline-success" role="status">{message}</p>}</>}
      {result&&<div className={styles.resultArea}><div className={styles.metricGrid}><div><span>转化提升</span><strong>{result.conversion_uplift_pp>=0?"+":""}{result.conversion_uplift_pp.toFixed(1)}pp</strong></div><div><span>增量订单</span><strong>{result.incremental_orders.toFixed(1)}</strong></div><div><span>增量收入</span><strong>{money(result.incremental_revenue,result.currency)}</strong></div><div><span>ROI</span><strong>{result.roi==null?"成本为 0":`${(result.roi*100).toFixed(0)}%`}</strong></div></div><div className={styles.provenance}><strong>商家回传 · 未独立核验</strong><span>归因窗口 {result.attribution_window_days} 天 · {result.revenue_net_of_refunds?"收入已扣退款":"收入未确认扣除退款"}</span></div>{message&&<p className="inline-success" role="status">{message}</p>}</div>}
    </section>
    <section className={styles.demoHeading}><div><p className="eyebrow">SYNTHETIC DEMO</p><h2>演示学习结果</h2></div><span>不代表真实经营收益</span></section><section className="content-grid learning-grid"><article className="card results-card"><div className="card-kicker"><StatusBadge tone="warning">DEMO</StatusBadge><span>合成示例结果</span></div><h2>高流失风险客户召回 A/B 测试</h2><div className="results-bars"><div><span>实验组转化率</span><strong>20.0%</strong><i style={{width:"80%"}}/></div><div><span>对照组转化率</span><strong>10.0%</strong><i className="control" style={{width:"40%"}}/></div></div><p>归因逻辑：在相同观察窗内，计算实验组相对对照组的增量转化与对应订单收入。</p></article><article className="card caution-card"><p className="eyebrow">Guardrails</p><h3>结论使用边界</h3><ul><li>样本量不足时，不做扩量推荐。</li><li>未接入渠道回执时，不能声称“已触达”。</li><li>没有成本数据时，不展示真实 ROI。</li><li>商家手工回传结果不等于平台独立核验。</li></ul></article></section>
  </main>;
}
